name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install and Build 🔧
        run: |
          npm ci --ignore-scripts --no-audit --no-fund --no-progress --prefer-offline
          cd modules
          cd generator
          npm run build
          cd ..
          cd app
          npm ci --ignore-scripts --no-audit --no-fund --no-progress --prefer-offline
          npm link ../generator
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: modules/app/build
